#!/usr/bin/env python3
"""Bundle config + robot + mission(s) into ONE file for the SPIKE App.
(The SPIKE App 3 only runs a single Python file, so we glue the pieces together.)

  python build.py                 -> list missions
  python build.py m01_example     -> build/m01_example.py   (one mission)
  python build.py all             -> build/all_missions.py  (menu: LEFT=next, RIGHT=start)
Then copy the file's text into a new Python project in the SPIKE App.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
MISSIONS = ROOT / "missions"
OUT = ROOT / "build"
IMPORT_RE = re.compile(r"^[ \t]*from[ \t]+(config|robot)[ \t]+import[ \t]+.*$", re.M)
HEADER = "# AUTO-GENERATED by build.py - do not edit here. Edit the files in the repo.\n"


def names():
    return sorted(p.stem for p in MISSIONS.glob("*.py") if not p.stem.startswith("_"))


def read(path):
    return IMPORT_RE.sub("", path.read_text())


def mission_code(name):
    src = read(MISSIONS / (name + ".py"))
    if "async def run(" not in src:
        sys.exit("ERROR: %s.py has no 'async def run():'" % name)
    return src.replace("async def run(", "async def run_%s(" % name)


def bundle(chosen):
    parts = [HEADER, read(ROOT / "config.py"), read(ROOT / "robot.py")]
    parts += [mission_code(n) for n in chosen]
    if len(chosen) == 1:
        n = chosen[0]
        parts.append(
            "\nasync def main():\n"
            "    await init()\n"
            "    await wait_for_button()   # press RIGHT button to start\n"
            "    await run_%s()\n\n"
            "runloop.run(main())\n" % n)
    else:
        items = []
        for n in chosen:
            m = re.match(r"m(\d+)", n)
            items.append('("%s", run_%s)' % (str(int(m.group(1))) if m else n, n))
        parts.append(
            "\nasync def main():\n"
            "    await init()\n"
            "    await menu([%s])\n\n"
            "runloop.run(main())\n" % ", ".join(items))
    return "\n".join(parts)


def main():
    available = names()
    if len(sys.argv) < 2:
        print("Missions:", ", ".join(available))
        print("Usage: python build.py <mission_name | all>")
        return
    arg = sys.argv[1].replace(".py", "")
    if arg == "all":
        chosen = [n for n in available if n != "template"]
        out_name = "all_missions"
    elif arg in available:
        chosen, out_name = [arg], arg
    else:
        sys.exit("Unknown mission '%s'. Available: %s" % (arg, ", ".join(available)))
    OUT.mkdir(exist_ok=True)
    out = OUT / (out_name + ".py")
    out.write_text(bundle(chosen))
    print("Built", out, "- paste its contents into the SPIKE App.")


main()